import {
  Activity,
  Apple,
  Baby,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  Coffee,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Hotel,
  Lightbulb,
  MapPin,
  Monitor,
  Music,
  Package,
  Pill,
  PiggyBank,
  Plane,
  Receipt,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  Smartphone,
  Sofa,
  Train,
  Tv,
  UtensilsCrossed,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface CategoryIcon {
  name: string;
  label: string;
  Icon: LucideIcon;
}

export const CATEGORY_ICONS: CategoryIcon[] = [
  { name: "Utensils", label: "Dining", Icon: Utensils },
  { name: "UtensilsCrossed", label: "Restaurant", Icon: UtensilsCrossed },
  { name: "Coffee", label: "Coffee", Icon: Coffee },
  { name: "Apple", label: "Groceries", Icon: Apple },
  { name: "ShoppingCart", label: "Shopping cart", Icon: ShoppingCart },
  { name: "ShoppingBag", label: "Shopping bag", Icon: ShoppingBag },
  { name: "Car", label: "Car", Icon: Car },
  { name: "Bus", label: "Bus", Icon: Bus },
  { name: "Train", label: "Train", Icon: Train },
  { name: "Plane", label: "Flight", Icon: Plane },
  { name: "Fuel", label: "Fuel", Icon: Fuel },
  { name: "MapPin", label: "Local travel", Icon: MapPin },
  { name: "Globe", label: "Travel", Icon: Globe },
  { name: "Hotel", label: "Hotel", Icon: Hotel },
  { name: "Home", label: "Home", Icon: Home },
  { name: "Sofa", label: "Furniture", Icon: Sofa },
  { name: "Lightbulb", label: "Electricity", Icon: Lightbulb },
  { name: "Droplets", label: "Water", Icon: Droplets },
  { name: "Wifi", label: "Internet", Icon: Wifi },
  { name: "Flame", label: "Gas", Icon: Flame },
  { name: "Zap", label: "Utilities", Icon: Zap },
  { name: "Heart", label: "Health", Icon: Heart },
  { name: "Activity", label: "Fitness", Icon: Activity },
  { name: "Pill", label: "Medicine", Icon: Pill },
  { name: "Dumbbell", label: "Gym", Icon: Dumbbell },
  { name: "Wallet", label: "Wallet", Icon: Wallet },
  { name: "CreditCard", label: "Card", Icon: CreditCard },
  { name: "PiggyBank", label: "Savings", Icon: PiggyBank },
  { name: "Banknote", label: "Cash", Icon: Banknote },
  { name: "Receipt", label: "Bills", Icon: Receipt },
  { name: "BookOpen", label: "Education", Icon: BookOpen },
  { name: "GraduationCap", label: "School", Icon: GraduationCap },
  { name: "Briefcase", label: "Work", Icon: Briefcase },
  { name: "Building2", label: "Office", Icon: Building2 },
  { name: "Monitor", label: "Electronics", Icon: Monitor },
  { name: "Smartphone", label: "Phone", Icon: Smartphone },
  { name: "Tv", label: "TV", Icon: Tv },
  { name: "Film", label: "Movies", Icon: Film },
  { name: "Music", label: "Music", Icon: Music },
  { name: "Gift", label: "Gifts", Icon: Gift },
  { name: "Shirt", label: "Clothing", Icon: Shirt },
  { name: "Scissors", label: "Personal care", Icon: Scissors },
  { name: "Baby", label: "Kids", Icon: Baby },
  { name: "Dog", label: "Pets", Icon: Dog },
  { name: "Package", label: "Delivery", Icon: Package },
  { name: "Wrench", label: "Repairs", Icon: Wrench },
] as const;

export const CATEGORY_ICON_MAP = new Map<string, LucideIcon>(
  CATEGORY_ICONS.map(({ name, Icon }) => [name, Icon]),
);

export function getCategoryIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return CATEGORY_ICON_MAP.get(name) ?? null;
}
