-- Planned Commitments and Loans: first-class financial planning concepts.
--
-- PLANNED COMMITMENTS replace the manual-bill concept semantically. A planned
-- commitment is a named, forward-looking obligation (insurance premium, school
-- fee, subscription, rent) with its own payment frequency and an optional saving
-- cadence (pay quarterly but save monthly). The commitment_reserve in
-- Safe-to-Spend is the sum of all upcoming occurrences' amount_minor -- a
-- logical reserve that prevents the user from accidentally spending cash
-- earmarked for a known future payment.
--
-- LOANS are a parallel first-class concept: a named liability with lender,
-- rate, installment schedule, and outstanding balance. Each loan's installment
-- generates its own commitment reserve entry in the Upcoming view.
--
-- Neither feature moves money. A planned contribution to a commitment is NOT an
-- actual bank transfer. Only an explicit user action that records/adds the
-- payment can change actual account balances.

create type commitment_status as enum ('active', 'paused', 'completed', 'cancelled');
create type commitment_tenure_type as enum ('none', 'n_payments', 'end_date');
create type commitment_occurrence_status as enum ('upcoming', 'paid', 'skipped');
create type loan_type as enum ('home', 'car', 'personal', 'education', 'business', 'other');
create type loan_status as enum ('active', 'completed', 'cancelled');

-- planned_commitments: the canonical record of a recurring financial obligation.
create table planned_commitments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id),
  -- Human-readable name (replaces bill_definitions.merchant_pattern).
  name text not null,
  category_id uuid references categories(id),
  -- The payment amount. amount_is_estimate = true for variable-amount bills
  -- (e.g. electricity) where the user enters a typical/expected amount.
  amount_minor bigint not null,
  amount_is_estimate boolean not null default false,
  currency text not null default 'INR',
  -- How often the payment actually occurs (quarterly, monthly, yearly, etc.).
  payment_frequency recurrence_interval not null,
  -- The next due date for this commitment's next payment.
  next_payment_date date not null,
  -- OPTIONAL progressive saving: if set, the user intends to set aside
  -- saving_amount_minor each saving_cadence period toward the next payment.
  -- E.g. quarterly ₹15k payment with monthly ₹5k saving cadence.
  -- NULL means no saving plan; the full amount is reserved at once.
  saving_cadence recurrence_interval,
  saving_amount_minor bigint,
  -- The account from which this commitment will be paid.
  funding_account_id uuid references accounts(id),
  -- How long this commitment runs: none (indefinite), n_payments, or end_date.
  tenure_type commitment_tenure_type not null default 'none',
  tenure_payments int,
  tenure_end_date date,
  status commitment_status not null default 'active',
  notes text,
  -- Migration tracking: which manual bill_definition this was migrated from.
  migrated_from_bill_id uuid references bill_definitions(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint planned_commitments_saving_pair_check
    check (
      (saving_cadence is null and saving_amount_minor is null) or
      (saving_cadence is not null and saving_amount_minor is not null)
    ),
  constraint planned_commitments_tenure_payments_check
    check (tenure_type <> 'n_payments' or tenure_payments is not null),
  constraint planned_commitments_tenure_end_date_check
    check (tenure_type <> 'end_date' or tenure_end_date is not null)
);

-- planned_commitment_occurrences: one row per upcoming/past payment instance.
-- Generated by application logic when a commitment is created or rolls over.
create table planned_commitment_occurrences (
  id uuid primary key default gen_random_uuid(),
  commitment_id uuid not null references planned_commitments(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  -- The date this payment is due.
  due_date date not null,
  -- The expected payment amount for this occurrence.
  amount_minor bigint not null,
  -- The logically reserved amount so far (0 <= reserved_minor <= amount_minor).
  -- Grows each saving_cadence period via application logic.
  -- For commitments without a saving plan, starts at amount_minor (full reserve).
  reserved_minor bigint not null default 0,
  status commitment_occurrence_status not null default 'upcoming',
  -- Linked once the payment is recorded as an actual transaction.
  matched_transaction_id uuid references transactions(id),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planned_commitment_occurrences_reserved_check
    check (reserved_minor >= 0 and reserved_minor <= amount_minor)
);

-- loans: a named liability with scheduled installments.
create table loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id),
  -- Human-readable name (e.g. "Home Loan - HDFC", "Car Loan - ICICI").
  name text not null,
  lender_name text,
  loan_type loan_type not null default 'other',
  -- Original principal borrowed.
  principal_minor bigint not null,
  -- Annual interest rate (e.g. 8.5 for 8.5%). Nullable for 0% interest loans.
  interest_rate_pct numeric(6, 3),
  currency text not null default 'INR',
  start_date date,
  end_date date,
  repayment_frequency recurrence_interval not null default 'monthly',
  -- Fixed installment amount (EMI). The user enters this directly.
  installment_amount_minor bigint not null,
  -- Next scheduled installment date.
  next_payment_date date,
  -- Account from which installments are paid.
  payment_account_id uuid references accounts(id),
  -- Current outstanding balance (user-entered, not computed from transactions).
  outstanding_minor bigint,
  status loan_status not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- RLS: all tables are user-isolated (own rows only).
alter table planned_commitments enable row level security;
create policy "Users own their planned commitments"
  on planned_commitments for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

alter table planned_commitment_occurrences enable row level security;
create policy "Users own their commitment occurrences"
  on planned_commitment_occurrences for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

alter table loans enable row level security;
create policy "Users own their loans"
  on loans for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Indexes for the read patterns used by Safe-to-Spend and the Upcoming page.
create index planned_commitments_user_active_idx
  on planned_commitments(user_id, next_payment_date)
  where deleted_at is null and status = 'active';

create index planned_commitment_occurrences_user_upcoming_idx
  on planned_commitment_occurrences(user_id, due_date)
  where status = 'upcoming';

create index planned_commitment_occurrences_commitment_idx
  on planned_commitment_occurrences(commitment_id);

create index loans_user_active_idx
  on loans(user_id, next_payment_date)
  where deleted_at is null and status = 'active';
